-- DROP TABLE IF EXISTS TB_HEROIS;

-- CREATE TABLE TB_HEROIS (
--     ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
--     NOME TEXT NOT NULL,
--     PODER TEXT NOT NULL
-- );
-- --create
-- INSERT INTO TB_HEROIS (NOME, PODER) 
-- VALUES 
-- ('FLASH', 'VELOCIDADE'),
-- ('AQUAMAN', 'FALAR COM OS ANIMAIS'),
-- ('BATMAN', 'DINHEIRO')

-- --read
-- SELECT * FROM TB_HEROIS;
-- SELECT * FROM TB_HEROIS WHERE NOME = 'FLASH'

-- -- update
-- UPDATE TB_HEROIS
-- SET NOME = 'GOKU', PODER = 'DEUS'
-- WHERE ID = 1;

-- -- delete
-- DELETE FROM TN_HEROIS WHERE ID=2;